### ISSUE TITLE
Implement an hdf5_file interface

### ISSUE THREAD

**Issue by pbtoast** [polymec/polymec-dev#266]
Silo is becoming more and more of a hindrance, as it gets longer and longer in the tooth. Its last release was in 2014. It would be nice to have a basic HDF5 file format to fall back on. This forces the issue of finding appropriate viz tools, but given the merits of sticking to 2D plots (vs just making pretty 3D pictures), I think it's worth it just to have a file format that can hold 3D simulation data, whether or not it can be viewed as such.

**Comment by jjphatt** [comment]
This is important, but it's not exactly tech debt anymore, now that Silo is back up and running.

**Comment by pbtoast** [comment]
Without a tool to visualize geometries, there's not much point in pursuing this at the moment. Perhaps another solution will present itself.
